vich_uploader:
    db_driver: orm
    
    mappings:
        reclamation_files:
            uri_prefix: /uploads/reclamations
            upload_destination: '%kernel.project_dir%/public/uploads/reclamations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 