# config/routes.yaml
admin_controllers:
  resource:
    path: "../src/Controller/Admin/"
    namespace: App\Controller\Admin
  type: attribute
  prefix: /admin
  
controllers:
  resource: ../src/Controller/**/*
  type: attribute
  exclude: "../src/Controller/Admin/"

hwi_oauth_connect:
    resource: '@HWIOAuthBundle/Resources/config/routing/connect.xml'
    prefix: /connect

hwi_oauth_login:
    resource: '@HWIOAuthBundle/Resources/config/routing/login.xml'
    prefix: /login

hwi_oauth_redirect:
    resource: '@HWIOAuthBundle/Resources/config/routing/redirect.xml'
    prefix: /connect

google_login:
    path: /connect/google
    defaults:
        _controller: 'HWI\Bundle\OAuthBundle\Controller\ConnectController::redirectToServiceAction'
        service: google

# Catch-all route to redirect to the 404 page
not_found:
    path: /{req<.+>}
    controller: App\Controller\FrontOffice\ErrorController::notFound