# config/services.yaml

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    evenements_directory: '%kernel.project_dir%/public/uploads/evenements'
    turnstile_site_key: '%env(resolve:TURNSTILE_SITE_KEY)%'
    turnstile_secret_key: '%env(resolve:TURNSTILE_SECRET_KEY)%'
    weather_api_key: '%env(resolve:WEATHER_API_KEY)%'
    huggingface_api_key: '%env(HUGGINGFACE_API_KEY)%'
    admin_email: 'maram.rachdi11@gmail.com'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\TurnstileValidator:
        arguments:
            $secret: '%turnstile_secret_key%'

    App\EventListener\TurnstileLoginListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }

    App\Service\WeatherService:
        arguments:
            $weatherApiKey: '%weather_api_key%'

    App\Service\SentimentAnalysisService:
        arguments:
            $apiKey: '%huggingface_api_key%'

    App\Service\EmbeddingService:
        arguments:
            $huggingFaceApiKey: '%huggingface_api_key%'
            $httpClient: '@http_client'
            $logger: '@monolog.logger'

    App\Controller\MatchingController:
        arguments:
            $logger: '@monolog.logger'

    App\Service\MatchingService:
        arguments:
            $pdfParserService: '@App\Service\PdfParserService'
            $embeddingService: '@App\Service\EmbeddingService'
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@monolog.logger'

    App\Controller\AnalyseCvController:
        arguments:
            $logger: '@monolog.logger'
            $entityManager: '@doctrine.orm.entity_manager'
    App\Service\EmailNotificationService:
        arguments:
            $adminEmail: '%admin_email%'
