# config/services.yaml

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    evenements_directory: '%kernel.project_dir%/public/uploads/evenements'
    turnstile_site_key: '%env(resolve:TURNSTILE_SITE_KEY)%'
    turnstile_secret_key: '%env(resolve:TURNSTILE_SECRET_KEY)%'
    weather_api_key: '%env(resolve:WEATHER_API_KEY)%'
    huggingface_api_key: '%env(HUGGINGFACE_API_KEY)%'
    infobip_api_url: '%env(INFOBIP_API_URL)%'
    infobip_api_key: '%env(INFOBIP_API_KEY)%'
    infobip_sender: '%env(INFOBIP_SENDER)%'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # Ajoutez ce service
    App\Service\InfobipSmsSender:
        arguments:
            $client: '@http_client'
            $apiUrl: '%env(INFOBIP_API_URL)%'
            $apiKey: '%env(INFOBIP_API_KEY)%'
            $sender: '%env(INFOBIP_SENDER)%'
            $defaultPhoneNumber: '%env(DEFAULT_SMS_RECIPIENT)%'


    App\Security\TurnstileValidator:
        arguments:
            $secret: '%turnstile_secret_key%'

    App\EventListener\TurnstileLoginListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }

    App\Service\WeatherService:
        arguments:
            $weatherApiKey: '%weather_api_key%'

    App\Service\SentimentAnalysisService:
        arguments:
            $apiKey: '%huggingface_api_key%'

